# Generated by Django 3.1.7 on 2021-04-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210419_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemen',
            old_name='availabity',
            new_name='is_available',
        ),
    ]
