# Generated by Django 3.1.7 on 2021-04-19 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_auto_20210414_1622'),
        ('accounts', '0002_auto_20210419_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('servicemen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.servicemen')),
            ],
        ),
    ]
