# Generated by Django 3.1.7 on 2021-04-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicemen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcceptOrder',
        ),
    ]
