# Generated by Django 3.1.7 on 2021-04-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210414_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Reviewed', 'Reviewed'), ('Expert Assigned', 'Expert Assigned'), ('Working', 'Working'), ('Finished', 'Finished')], default='Pending', max_length=200, null=True),
        ),
    ]
